name: Prod commit Heroku
on:
  push:
    branches:
      - master
jobs:
  # This workflow contains "deploy"
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Init project
        uses: actions/checkout@v2

      - name: Add Nodejs
        # add Node for Vuejs
        uses: actions/setup-node@master

      - name: Install dependances
        # allow to run npm
        run: sudo npm ci

      - name: Run Lint
        # fix problems in JavaScript code
        run: sudo npm run lint

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
